# Problem Formulation and the Hubbard Model

This module is built around the abstract class `ProblemFormulation`, which provides a framework for quantum many-body problem formulation. It is divided into two main abstract classes: `OneBodyProblemFormulation` and `ManyBodyProblemFormulation`, designed to describe the Hamiltonian and density matrix for single-particle and many-particle systems, respectively.

`HubbardFormulation.py` implements the concrete Hubbard model, including `OneBodyHubbardFormulation` and `ManyBodyHubbardFormulation`, which can be used to simulate electron hopping and interactions on a lattice.

## Customizing the Hamiltonian

To define a custom Hamiltonian, subclass `OneBodyProblemFormulation` or `ManyBodyProblemFormulation` and implement the abstract methods to specify the desired Hamiltonian parameters and structure.

## Example Usage

Below are examples of how to use `OneBodyHubbardFormulation` and `ManyBodyHubbardFormulation` to build a Hubbard model and compute quantities such as the Hamiltonian, analytic solution, and density matrix.

In [1]:
from DMET.ProblemFormulation.Hubbard.HubbardFormulation import OneBodyHubbardFormulation

# Parameter settings
L = 4  # Number of lattice sites
number_of_electrons = 4  # Number of electrons
hopping_t = 1.0  # Hopping parameter

# Create one-body Hubbard model
onebody = OneBodyHubbardFormulation(L, hopping_t, number_of_electrons)

# Get Hamiltonian
H = onebody.get_hamiltonian()
print('One-body Hamiltonian:', H)

# Analytic solution: ground state energy and wavefunction
energy, wf = onebody.get_analytic_solution(number_of_electrons)
print('Ground state energy:', energy)
print('Wavefunction shape:', wf.shape)

# Density matrix
density_matrix = onebody.get_density_matrix()
print('Density matrix:', density_matrix)

One-body Hamiltonian: -1.0 [0^ 2] +
-1.0 [0^ 6] +
-1.0 [1^ 3] +
-1.0 [1^ 7] +
-1.0 [2^ 0] +
-1.0 [2^ 4] +
-1.0 [3^ 1] +
-1.0 [3^ 5] +
-1.0 [4^ 2] +
-1.0 [4^ 6] +
-1.0 [5^ 3] +
-1.0 [5^ 7] +
-1.0 [6^ 0] +
-1.0 [6^ 4] +
-1.0 [7^ 1] +
-1.0 [7^ 5]
Ground state energy: -4.0
Wavefunction shape: (8, 4)
Density matrix: [[0.5  0.   0.25 0.   0.   0.   0.25 0.  ]
 [0.   0.5  0.   0.25 0.   0.   0.   0.25]
 [0.25 0.   0.5  0.   0.25 0.   0.   0.  ]
 [0.   0.25 0.   0.5  0.   0.25 0.   0.  ]
 [0.   0.   0.25 0.   0.5  0.   0.25 0.  ]
 [0.   0.   0.   0.25 0.   0.5  0.   0.25]
 [0.25 0.   0.   0.   0.25 0.   0.5  0.  ]
 [0.   0.25 0.   0.   0.   0.25 0.   0.5 ]]


In [2]:
from DMET.ProblemFormulation.Hubbard.HubbardFormulation import ManyBodyHubbardFormulation

# Parameter settings
L = 4  # Number of lattice sites
hopping_t = 1.0  # Hopping parameter
U = 2.0  # Interaction strength

# Create many-body Hubbard model
manybody = ManyBodyHubbardFormulation(L, hopping_t, U)

# Get Hamiltonian and decomposed terms
H, onebody_terms, twobody_terms = manybody.get_hamiltonian()
print('Many-body Hamiltonian:', H)
print('One-body terms:', onebody_terms)
print('Two-body terms:', twobody_terms)

Many-body Hamiltonian: 2.0 [0^ 1^ 1 0] +
-1.0 [0^ 2] +
-1.0 [0^ 6] +
-1.0 [1^ 3] +
-1.0 [1^ 7] +
-1.0 [2^ 0] +
2.0 [2^ 3^ 3 2] +
-1.0 [2^ 4] +
-1.0 [3^ 1] +
-1.0 [3^ 5] +
-1.0 [4^ 2] +
2.0 [4^ 5^ 5 4] +
-1.0 [4^ 6] +
-1.0 [5^ 3] +
-1.0 [5^ 7] +
-1.0 [6^ 0] +
-1.0 [6^ 4] +
2.0 [6^ 7^ 7 6] +
-1.0 [7^ 1] +
-1.0 [7^ 5]
One-body terms: [[ 0.  0. -1.  0.  0.  0. -1.  0.]
 [ 0.  0.  0. -1.  0.  0.  0. -1.]
 [-1.  0.  0.  0. -1.  0.  0.  0.]
 [ 0. -1.  0.  0.  0. -1.  0.  0.]
 [ 0.  0. -1.  0.  0.  0. -1.  0.]
 [ 0.  0.  0. -1.  0.  0.  0. -1.]
 [-1.  0.  0.  0. -1.  0.  0.  0.]
 [ 0. -1.  0.  0.  0. -1.  0.  0.]]
Two-body terms: [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 2. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
 

## Custom Hamiltonian Example

Below are code examples for defining your own Hamiltonian. Comments indicate which attributes and methods are <b>must required</b> or <b>optional</b> for each type of problem formulation, based on the abstract class definitions in <code>ProblemFormulation.py</code>.

### Introduction to OneBodyProblemFormulation in DMET

The `OneBodyProblemFormulation` abstract class provides a framework for defining quantum many-body problems where the Hamiltonian consists only of one-body terms (i.e., terms that describe single-particle hopping or potential energies, but no explicit particle-particle interactions). In DMET (Density Matrix Embedding Theory), this class is used to model systems where electron correlations are either absent or treated at the mean-field level.

#### How It Works in DMET

In DMET, the `OneBodyProblemFormulation` is typically subclassed to implement specific models, such as the non-interacting Hubbard model. The subclass must define methods to construct the one-body Hamiltonian, solve for its ground state (often analytically), and compute the corresponding density matrix. These quantities are essential for DMET's embedding procedure, which partitions the system into fragments and environments, allowing for efficient and accurate treatment of quantum correlations.

By using `OneBodyProblemFormulation`, DMET can:
- Build the one-body Hamiltonian matrix for the system.
- Obtain analytic solutions for the ground state energy and wavefunction.
- Calculate the one-body density matrix, which is used to match fragment and environment properties during the embedding process.

This abstraction enables flexible customization and extension to different lattice models or physical systems within the DMET framework.

In [3]:
from DMET.ProblemFormulation.ProblemFormulation import OneBodyProblemFormulation

class MyCustomOneBodyFormulation(OneBodyProblemFormulation):
    def __init__(self):
        super().__init__()
        # Optional: Set one-body terms as an attribute
        self.onebody_terms = ...  # e.g., numpy array

    def get_hamiltonian(self):
        # Optional: Construct and return your custom Hamiltonian
        pass

    def get_density_matrix(self):
        # Must required: Compute and return the density matrix
        pass

### Introduction to ManyBodyProblemFormulation in DMET

The `ManyBodyProblemFormulation` abstract class provides a framework for quantum many-body problems where the Hamiltonian includes both one-body and two-body interaction terms. This class is essential for modeling systems with explicit electron-electron interactions, such as the full Hubbard model or other correlated lattice models.

#### How It Works in DMET

In DMET, the `ManyBodyProblemFormulation` is subclassed to implement specific interacting models. The subclass must define methods to construct the many-body Hamiltonian, typically as a sum of one-body and two-body operators, and provide access to these terms for embedding calculations. This abstraction enables DMET to treat quantum correlations beyond mean-field, allowing for accurate simulation of strongly correlated systems.

By using `ManyBodyProblemFormulation`, DMET can:
- Build the many-body Hamiltonian with both hopping and interaction terms.
- Decompose the Hamiltonian into one-body and two-body components for embedding.
- Support flexible customization for different physical models and interaction structures.

This class is a key component for extending DMET to a wide range of correlated electron problems.

In [4]:
from DMET.ProblemFormulation.ProblemFormulation import ManyBodyProblemFormulation

class MyCustomManyBodyFormulation(ManyBodyProblemFormulation):
    def __init__(self):
        super().__init__()
        # Must required: Set one-body and two-body terms as attributes
        self.onebody_terms = ...  # e.g., numpy array
        self.twobody_terms = ...  # e.g., numpy array

    def get_hamiltonian(self):
        # Optional: Construct and return your custom many-body Hamiltonian
        pass